# Generated by Django 3.0.8 on 2020-07-18 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('cover', models.URLField(null=True)),
                ('released_on', models.DateTimeField(default=datetime.datetime.now)),
                ('added_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('image', models.URLField(null=True)),
                ('about', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.URLField(null=True)),
                ('website', models.URLField(null=True)),
                ('about', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('alt_title', models.CharField(max_length=300)),
                ('url', models.URLField(unique=True)),
                ('rating', models.IntegerField(default=0)),
                ('length', models.FloatField(default=0)),
                ('added_on', models.DateTimeField(default=datetime.datetime.now)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_album', to='music_library.Album')),
                ('artist', models.ManyToManyField(related_name='track_artist', to='music_library.Artist')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.URLField(null=True)),
                ('author', models.ManyToManyField(related_name='lyric_author', to='music_library.Artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_track', to='music_library.Track')),
            ],
            options={
                'verbose_name': 'Lyric',
                'verbose_name_plural': 'Lyrics',
            },
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['name'], name='idx_language_name'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='idx_genre_name'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='idx_company_name'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['name'], name='idx_artist_name'),
        ),
        migrations.AddField(
            model_name='album',
            name='casting',
            field=models.ManyToManyField(related_name='album_casting', to='music_library.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='composed_by',
            field=models.ManyToManyField(related_name='album_composed_by', to='music_library.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_genre', to='music_library.Genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_language', to='music_library.Language'),
        ),
        migrations.AddField(
            model_name='album',
            name='released_by',
            field=models.ManyToManyField(related_name='album_released_by', to='music_library.Company'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['title'], name='idx_track_title'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['name'], name='idx_album_name'),
        ),
    ]
